// 06.React/day03-非受控组件Ref&组件通讯/shopping-cart/src/components/CartList/index.jsx
import React from "react"


class CartList extends React.Component {

  handlerDelete = (id)=>{
    this.props.deleteItem(id);
  }

  //改变数量事件
  handleChangeNum = (id,e) => {
    // console.log(e.target.dataset.num);
    //判断用户点击元素
    switch (e.target.dataset.num) {
      case 'add':
        this.props.changeNum(id,'add');
        break;
    
      case 'min':
        this.props.changeNum(id,'min');
        break;
      
      case 'blur':
        this.props.changeNum(id,'blur',e.target.value);
        break;
    }
  }

  render() {
    return (
      <div>
        {
          this.props.list.map(item=>(
            <div className="item" key={item.id}>
            <img src={item.img} alt="" />
            <div className="name">{item.name}</div>
            <div className="change">
              {/* eslint-disable-next-line */}
              <a href="#" data-num='min' onClick={this.handleChangeNum.bind(this,item.id)}>－</a>
              <input type="text" className="num" data-num='blur' value={item.num} onChange={this.handleChangeNum.bind(this,item.id)}/>
              {/* eslint-disable-next-line */}
              <a href="#" data-num='add' onClick={this.handleChangeNum.bind(this,item.id)}>＋</a>
            </div>
            <div className="del" onClick={this.handlerDelete.bind(this,item.id)}>×</div>
          </div>
          ))
        }
      </div>
    )
  }
}

export default CartList;

// 08.TSCourse-main/day09-案例/vite_cart/src/components/CartList/index.vue
<template>
  <!-- 列表 -->
  <div>
    <div class="item" v-for="item in cartItem" :key="item.id">
      <img :src="item.img" />
      <div class="name">{{item.name}}</div>
      <div class="change">
        <a href="#" @click="handleMinxItem(item.id)">－</a>
        <input type="text" class="num" :value="item.num" @blur="handleChangeItem($event,item.id)"/>
        <a href="#" @click="handleAddItem(item.id)">＋</a>
      </div>
      <div class="del" @click="handleDeleteItem($event,item.id)">×</div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";


export default defineComponent({
    name: "CartList",
    props: {
        cartItem: {
            type: Array,
            required: true
        }
    },
    setup(props,{emit}){
        const handleDeleteItem = function(event: MouseEvent , id:number){
            emit('del',id);
        }

        const handleChangeItem = function(event:any , id:number){
            let result = event.target.value;
            console.log(event.target.value);
            emit('change-num',id ,'change', result);
        }

        const handleAddItem = function(id:number){
            
            emit('change-num',id ,'add');
        }

        const handleMinxItem = function(id:number){
            emit('change-num',id,'remove');
        }
        
        return{
            handleDeleteItem,
            handleChangeItem,
            handleAddItem,
            handleMinxItem
        }
    }
});
</script>

<style>
</style>
