// 08.TSCourse-main/day09-案例/vite_cart/src/components/CartList/index.vue
<template>
  <!-- 列表 -->
  <div>
    <div class="item" v-for="item in cartItem" :key="item.id">
      <img :src="item.img" />
      <div class="name">{{item.name}}</div>
      <div class="change">
        <a href="#" @click="handleMinxItem(item.id)">－</a>
        <input type="text" class="num" :value="item.num" @blur="handleChangeItem($event,item.id)"/>
        <a href="#" @click="handleAddItem(item.id)">＋</a>
      </div>
      <div class="del" @click="handleDeleteItem($event,item.id)">×</div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";


export default defineComponent({
    name: "CartList",
    props: {
        cartItem: {
            type: Array,
            required: true
        }
    },
    setup(props,{emit}){
        const handleDeleteItem = function(event: MouseEvent , id:number){
            emit('del',id);
        }

        const handleChangeItem = function(event:any , id:number){
            let result = event.target.value;
            console.log(event.target.value);
            emit('change-num',id ,'change', result);
        }

        const handleAddItem = function(id:number){
            
            emit('change-num',id ,'add');
        }

        const handleMinxItem = function(id:number){
            emit('change-num',id,'remove');
        }
        
        return{
            handleDeleteItem,
            handleChangeItem,
            handleAddItem,
            handleMinxItem
        }
    }
});
</script>

<style>
</style>

// 06.React/day15-ReactHook/shopping-cart/src/components/CartList/index.jsx
import React from "react";

function CartList(props) {
  // 4.2 在事件的处理函数中, 调用父组件传给CartList的方法，并把参数传给这个方法
  const handlerDelete = (id) => {
    // console.log(id);
    props.deleteItem(id);
  };

  // 5.3 声明onChange事件的事件处理方法
  const handlerChange = (id, e) => {
    // 5.4 给父组件传: 1.type 2.id 3.num
    props.changeItem({
      type: "change",
      id: id,
      num: e.target.value,
    });
  };

  const handlerAdd = (id) => {
    props.changeItem({
      type: "add",
      id: id,
    });
  };

  const handlerMin = (id) => {
    props.changeItem({
      type: "min",
      id: id,
    });
  };

  // 1.3.渲染name
  return (
    <div>
      {props.list.map((item) => (
        <div className="item" key={item.id}>
          <img src={item.img} alt="" />
          <div className="name">{item.name}</div>
          <div className="change">
            {/* eslint-disable-next-line */}
            <a href="#" onClick={() => handlerMin(item.id)}>
              －
            </a>
            {/* 5.1.渲染list中的商品数量 */}
            {/* 5.2.在input中声明OnChange事件 */}
            <input
              type="text"
              className="num"
              value={item.num}
              onChange={(e) => handlerChange(item.id, e)}
            />
            {/* eslint-disable-next-line */}
            <a href="#" onClick={() => handlerAdd(item.id)}>
              ＋
            </a>
          </div>
          {/* 4.1 在CartList组件中 给删除按钮绑定事件(事件传参) */}
          <div className="del" onClick={() => handlerDelete(item.id)}>
            ×
          </div>

          {/* <div className="del" onClick={() => { this.props.deleteItem(item.id) }}>×</div> */}
        </div>
      ))}
    </div>
  );
}

export default CartList;
