// 08.TSCourse-main/day09-案例/vite_cart/src/components/CartTotal/index.vue
<template>
  <!-- 总价 -->
  <div class="total">
    <span>总价：{{cartTotal}}</span>
    <button>结算</button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CartTotal",
  props: {
    cartTotal: {
      type: Number,
      required: true,
    },
  },
  setup() {},
});
</script>

<style>
</style>

// 06.React/day15-ReactHook/shopping-cart/src/components/CartTotal/index.jsx
import React from "react"

function CartTotal(props) {

  // 2.3.定义一个方法 用来计算总价
  const comutedTotal = () => {
    let sum = 0;
    props.list.forEach(item => {
      sum += item.price * item.num;
    });

    return sum;
  }

  // 1.3.渲染name
  return (
    <div className="total">
      <span>总价：{comutedTotal()}</span>
      <button>结算</button>
    </div>
  )
}

export default CartTotal
